test_metric_indexes:
- 1
- 2
- 3
- 4
- 5

optimizer: adam  #'adam', 'adamW' 'adamax', 'rms_prop', 'sgd'
discriminator_optimizer: adam  #'adam', 'adamW', 'adamax', 'RMSprop', 'sgd'
scheduler: OneCycle  #'ReduceOnPlateau', 'OneCycle', 'CosineDecay', 'MultiStepScheduler'
discriminator_lr_scheduler: OneCycle  #'ReduceOnPlateau', 'OneCycle', 'CosineDecay', 'MultiStepScheduler'
lr: 0.001
discriminator_lr: 0.001

seed: 666
batch_size: 4
num_epochs: 10
validation_split: 0.1
additional_folder: null

data_augmentation:
- "rotation"
- "horizontal_flip"
- "vertical_flip"

datagen_sampling_pdf: 0


